name: Generate EPUB from URLs

on:
  workflow_dispatch:
    inputs:
      URLS:
        description: 'List of URLs to include in the EPUB, separated by ;'
        required: true
        type: string
      send-to:
        description: 'Send to this email'
        type: string
        required: false
        default: gaitan@kindle.com
      commit:
        description: 'Commit the epub to the repo'
        required: false
        type: boolean
        default: false      
      

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        npm -g install @postlight/mercury-parser
        sudo apt-get install -y pandoc calibre
        pip install markdownify

    - name: Run script
      id: run-script
      env:
        URLS: ${{ inputs.URLS }}
      run: python news.py 

    - name: Send to kindle by mail
      uses: dawidd6/action-send-mail@v3
      if: inputs.send-to
      with:
        server_address: smtp.dreamhost.com
        server_port: 465
        secure: true
        username: calibre@nqnwebs.com
        password: ${{ secrets.MAIL_PASSWORD }}

        subject: New ebook
        to: ${{ inputs.send-to }}
        from: urls-to-ebook Github Action 
        # Optional plain body:
        body: New ebook!
        ignore_cert: true
        attachments: "*.mobi"
        
    - name: Commit and push
      if: inputs.commit
      run: |-
        rm *.epub
        mv *.mobi ebooks
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "New epub added ${timestamp}" || exit 0
        git push